export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAIL = "OTP_FAIL";
export const OTP_ERROR = "OTP_ERROR";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_ERROR = "UPDATE_USER_DETAILS_ERROR";

export const CHANGE_PASSWORD_RERQUEST = "CHANGE_PASSWORD_RERQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const FORGET_PASSWORD_RERQUEST = "FORGET_PASSWORD_RERQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";


export const SET_PASSWORD_RERQUEST = "SET_PASSWORD_RERQUEST";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";

// Questions constants

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_SCORE = "CHANGE_SCORE";

export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";

export const GET_QUIZZES = "GET_QUIZZES";

export const GET_LEADERBOARD_DATA_REQUEST = "GET_LEADERBOARD_DATA_REQUEST";
export const GET_LEADERBOARD_DATA_SUCCESS = "GET_LEADERBOARD_DATA_SUCCESS";
export const GET_LEADERBOARD_DATA_FAIL = "GET_LEADERBOARD_DATA_FAIL";
export const GET_LEADERBOARD_DATA_ERROR = "GET_LEADERBOARD_DATA_ERROR";
